server:
  port: 8086
  
spring:
  application:
    name: CONFIG-SERVER
      
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ajaz-SE/Microservice-config
          clone-on-start: true 